let shopItemsData = [
  {
    id: "a",
    name: "small shirt",
    price: 463,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-1.jpg",
  },
  {
    id: "b",
    name: "shirt",
    price: 200,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-2.jpg",
  },
  {
    id: "c",
    name: "t-shirt",
    price: 300,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-3.jpg",
  },
  {
    id: "d",
    name: "sma-shirt",
    price: 20,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-4.jpg",
  },
  {
    id: "e",
    name: "ful-shirt",
    price: 50,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-5.jpg",
  },
  {
    id: "f",
    name: "offical-shirt",
    price: 500,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-6.jpg",
  },
  {
    id: "g",
    name: "mens-dres",
    price: 60,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-7.jpg",
  },
  {
    id: "h",
    name: "suit",
    price: 53,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-8.jpg",
  },
  {
    id: "i",
    name: "ladies-shirt",
    price: 43,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-9.jpg",
  },
  {
    id: "j",
    name: "ladies-mens-item",
    price: 345,
    desc: "jjshf shdjl akjkahf kahf",
    img: "public/images/img-10.jpg",
  },
];
